### ISSUE TITLE
Tracker always shown

### ISSUE THREAD

**Issue by Obsidian007** [tehkrizz/Lua#1]
The tracker display will display the last TH notice received even after multiple days/zones. For instance, if I am on THF and kill a mob with TH on it it will remain displayed until I either quit FFXI orhit TH on another mob. It's not a big deal, but it would seem to make sense for the tracker to timeout after a certain amount of time or after zoning. I know I can manually turn the display off or reload the addon, but that seems a bit overkill. Just a suggestion.

**Comment by tehkrizz** [comment]
This issue has been resolved in the latest version.
